const sidebar=document.querySelector('#sidebar'),menu=document.querySelector('#menuButton'),backdrop=document.querySelector('#backdrop'),modal=document.querySelector('#modal'),toast=document.querySelector('#toast');let timer;
function notify(message){clearTimeout(timer);toast.querySelector('p').textContent=message;toast.classList.add('visible');timer=setTimeout(()=>toast.classList.remove('visible'),2600)}
function toggleMenu(force){const open=typeof force==='boolean'?force:!sidebar.classList.contains('open');sidebar.classList.toggle('open',open);backdrop.classList.toggle('visible',open);menu.setAttribute('aria-expanded',String(open));document.body.style.overflow=open?'hidden':''}
menu.addEventListener('click',()=>toggleMenu());backdrop.addEventListener('click',()=>toggleMenu(false));
document.querySelectorAll('.nav-item').forEach(item=>item.addEventListener('click',event=>{if(!document.querySelector(item.getAttribute('href'))){event.preventDefault();notify(`${item.dataset.placeholder} wird als Nächstes eingerichtet`)}document.querySelectorAll('.nav-item').forEach(link=>link.classList.remove('active'));item.classList.add('active');toggleMenu(false)}));
document.querySelectorAll('.reel-row').forEach(row=>row.addEventListener('click',()=>{document.querySelectorAll('.reel-row').forEach(item=>item.classList.remove('selected'));row.classList.add('selected');document.querySelector('#selectedTitle').textContent=row.dataset.reel;document.querySelector('#selectedViews').textContent=row.dataset.views;notify(`${row.dataset.reel} ausgewählt`)}));
document.querySelector('[data-edit]').addEventListener('click',()=>{const script=document.querySelector('#scriptContent');script.contentEditable='true';script.focus();notify('Du kannst das Skript jetzt bearbeiten')});
const periods=[{label:'7 Tage',values:['38,9K','2,1K','327','0,4%']},{label:'30 Tage',values:['152K','8,4K','1,2K','1,5%']},{label:'90 Tage',values:['428K','24K','3,7K','4,8%']}];let periodIndex=1;
document.querySelector('[data-period]').addEventListener('click',event=>{periodIndex=(periodIndex+1)%periods.length;const current=periods[periodIndex];event.currentTarget.textContent=`${current.label}⌄`;['views','likes','comments','growth'].forEach((key,index)=>document.querySelector(`[data-metric="${key}"]`).textContent=current.values[index]);notify(`Analyse: ${current.label}`)});
document.querySelectorAll('[data-toast]').forEach(button=>button.addEventListener('click',event=>{event.preventDefault();notify(button.dataset.toast)}));
document.querySelectorAll('[data-new]').forEach(button=>button.addEventListener('click',()=>modal.showModal()));document.querySelectorAll('[data-choice]').forEach(button=>button.addEventListener('click',()=>{modal.close();notify(`${button.dataset.choice} wurde ausgewählt`)}));modal.addEventListener('click',event=>{if(event.target===modal)modal.close()});document.addEventListener('keydown',event=>{if(event.key==='Escape')toggleMenu(false)});
