const sidebar=document.querySelector('#sidebar'),menu=document.querySelector('#menuButton'),backdrop=document.querySelector('#backdrop'),modal=document.querySelector('#modal'),toast=document.querySelector('#toast');let timer;
function notify(message){clearTimeout(timer);toast.querySelector('p').textContent=message;toast.classList.add('visible');timer=setTimeout(()=>toast.classList.remove('visible'),2600)}
function toggleMenu(force){const open=typeof force==='boolean'?force:!sidebar.classList.contains('open');sidebar.classList.toggle('open',open);backdrop.classList.toggle('visible',open);menu.setAttribute('aria-expanded',String(open));document.body.style.overflow=open?'hidden':''}
menu.addEventListener('click',()=>toggleMenu());backdrop.addEventListener('click',()=>toggleMenu(false));
const reels=[
  ['Hook in 3 Sekunden','@creatorlab','00:24','42,8K',98],['Storytelling-Formel','@socialtips','00:31','37,2K',91],['Content ohne Stress','@reelstudio','00:18','29,4K',86],['Die perfekte Caption','@marketingde','00:27','24,9K',79],['Mehr Reichweite','@growdaily','00:22','18,7K',72],
  ['5 Fehler bei Reels','@contentcoach','00:34','17,3K',70],['Der perfekte Einstieg','@hookmaster','00:19','16,8K',68],['Algorithmus einfach erklärt','@digitalwissen','00:42','15,1K',65],['Mehr Kommentare erhalten','@communitypro','00:25','13,9K',63],['Reels richtig planen','@planstudio','00:29','12,6K',61],
  ['Licht für dein Video','@filmtipps','00:21','11,8K',59],['Schneller Videoschnitt','@editacademy','00:37','10,9K',57],['Ideen für jeden Tag','@ideenwerk','00:26','9,7K',54],['Call-to-Action Vorlage','@conversionlab','00:20','8,8K',52],['Trend-Audio finden','@soundscout','00:23','7,9K',49],
  ['Kamera richtig einstellen','@videosetup','00:32','7,1K',47],['Bessere Untertitel','@captionpro','00:28','6,4K',44],['Authentisch vor der Kamera','@creatorlife','00:39','5,8K',41],['Reels mehrfach verwenden','@contentflow','00:30','5,2K',38],['Deine Wochenstrategie','@socialplan','00:45','4,7K',35]
];
const reelList=document.querySelector('#reelList'),reelSearch=document.querySelector('#reelSearch'),emptyState=document.querySelector('#emptyState');
function renderReels(query=''){const normalized=query.trim().toLowerCase();const visible=reels.filter(reel=>`${reel[0]} ${reel[1]}`.toLowerCase().includes(normalized));reelList.innerHTML=visible.map((reel,index)=>`<button class="reel-row ${reel[0]==='Hook in 3 Sekunden'?'selected':''}" data-reel="${reel[0]}" data-views="${reel[3]}"><span class="thumb t${index%5+1}"><i></i></span><span><strong>${reel[0]}</strong><small>${reel[1]} · ${reel[2]}</small></span><em><b>${reel[4]}%</b><i style="background:linear-gradient(90deg,#3e3d48 0 ${reel[4]}%,#e1e1e5 ${reel[4]}%)"></i></em></button>`).join('');emptyState.classList.toggle('visible',visible.length===0)}
renderReels();
reelSearch.addEventListener('input',()=>renderReels(reelSearch.value));
reelList.addEventListener('click',event=>{const row=event.target.closest('.reel-row');if(!row)return;openReel(row.dataset.reel,row.dataset.views,overviewContext)});

const dashboardView=document.querySelector('#dashboardView'),viewRoot=document.querySelector('#viewRoot');
const myReels=[['5 Content-Ideen für diese Woche','Heute, 10:24','Entwurf','draft','—','—'],['Warum dein Hook nicht funktioniert','Gestern, 18:42','Online','online','18,2K','1.309'],['Behind the Scenes: Mein Setup','27. Aug., 14:10','Online','online','31,7K','2.408'],['Die perfekte Caption schreiben','26. Aug., 09:35','Geplant','planned','—','—'],['Meine Wochenroutine','25. Aug., 17:20','Online','online','24,1K','1.862'],['3 Schnitt-Tricks für Anfänger','24. Aug., 12:05','Online','online','46,8K','3.711'],['Reichweite ohne Werbung','23. Aug., 08:48','Entwurf','draft','—','—'],['Content-Plan für September','22. Aug., 16:30','Geplant','planned','—','—'],['Hook in 3 Sekunden','21. Aug., 11:18','Online','online','42,8K','3.214'],['Mein kompaktes Licht-Setup','20. Aug., 18:06','Online','online','35,4K','2.761'],['Vorher und nachher: Videoschnitt','19. Aug., 13:44','Online','online','29,9K','2.118'],['So finde ich Trend-Audios','18. Aug., 09:12','Online','online','27,3K','1.984'],['Mehr Kommentare mit einer Frage','17. Aug., 17:55','Entwurf','draft','—','—'],['Untertitel, die gelesen werden','16. Aug., 12:20','Online','online','23,6K','1.742'],['Meine Kamera-Einstellungen','15. Aug., 08:36','Online','online','21,8K','1.559'],['Storytelling in 30 Sekunden','14. Aug., 19:08','Geplant','planned','—','—'],['Reels mehrfach verwenden','13. Aug., 14:28','Online','online','18,9K','1.306'],['Call to Action ohne Druck','12. Aug., 10:42','Online','online','17,4K','1.141'],['Drei Ideen gegen Content-Stress','11. Aug., 16:14','Entwurf','draft','—','—'],['Meine Wochenstrategie','10. Aug., 09:05','Online','online','14,7K','986']];
const reelRows=myReels.map((r,i)=>`<div class="table-row" data-open-reel data-title="${r[0]}" data-views="${r[4]}"><div class="item-main"><span class="item-thumb">▶</span><span><strong>${r[0]}</strong><small>${r[1]}</small></span></div><span class="status ${r[3]}">${r[2]}</span><span>${r[4]}</span><span>${r[5]}</span><button class="row-action" data-action="options">•••</button></div>`).join('');
const scripts=[['Hook-Bibliothek für Trends','Heute, 11:05','86 Wörter','Entwurf'],['Warum dein Reel nicht wächst','Gestern, 17:30','124 Wörter','Fertig'],['Behind the Scenes','25. Aug.','98 Wörter','Fertig'],['Content-Ideen im September','22. Aug.','142 Wörter','Entwurf'],['Storytelling in 30 Sekunden','18. Aug.','105 Wörter','Fertig']];
const scriptRows=scripts.map((s,i)=>`<div class="table-row"><div class="item-main"><span class="item-thumb">▤</span><span><strong>${s[0]}</strong><small>${s[1]}</small></span></div><span class="status ${s[3]==='Fertig'?'online':'draft'}">${s[3]}</span><span>${s[2]}</span><span>${i%2?'00:35':'00:28'}</span><button class="row-action" data-action="options">•••</button></div>`).join('');
const competitors=[['CL','Creator Lab','@creatorlab','284K','4,8M','8,7%'],['ST','Social Tipps','@socialtipps','196K','3,1M','7,9%'],['RS','Reel Studio','@reelstudio','142K','2,4M','9,2%'],['MD','Marketing DE','@marketingde','98K','1,7M','6,8%'],['GD','Grow Daily','@growdaily','76K','1,2M','8,1%'],['CC','Content Coach','@contentcoach','64K','980K','7,4%'],['HM','Hook Master','@hookmaster','58K','902K','8,4%'],['EA','Edit Academy','@editacademy','53K','844K','7,8%'],['CW','Caption Werk','@captionwerk','49K','791K','8,0%'],['SP','Social Plan','@socialplan','46K','738K','7,6%'],['VS','Video Setup','@videosetup','43K','694K','7,2%'],['SW','Story Werk','@storywerk','39K','641K','8,9%'],['TS','Trend Scout','@trendscout','36K','598K','9,1%'],['CM','Creator Mind','@creatormind','34K','552K','7,7%'],['RL','Reels Lab','@reelslab','31K','514K','8,3%'],['DA','Digital Alltag','@digitalalltag','29K','477K','7,5%'],['MF','Marketing Flow','@marketingflow','27K','438K','8,2%'],['VP','Video Praxis','@videopraxis','24K','392K','7,1%'],['IG','Ideen Garage','@ideengarage','22K','351K','8,6%'],['MP','Media Pro','@mediapro','19K','306K','7,3%']].map(c=>`<article class="competitor"><div class="competitor-top"><span class="competitor-avatar">${c[0]}</span><div><strong>${c[1]}</strong><small>${c[2]}</small></div><span class="trend-up">↗ aktiv</span></div><div class="competitor-stats"><div><span>Follower</span><strong>${c[3]}</strong></div><div><span>Aufrufe</span><strong>${c[4]}</strong></div><div><span>Engagement</span><strong>${c[5]}</strong></div></div></article>`).join('');

const views={
reels:`<div class="page-view reels-page"><header class="page-top"><div><small>DEINE INHALTE</small><h1>Meine Reels</h1><p>Plane, bearbeite und analysiere alle deine Kurzvideos.</p></div><div class="page-actions"><button class="ui-button">Importieren</button><button class="ui-button primary-action" data-action="new">＋ Neues Reel</button></div></header><div class="filter-bar"><label>⌕<input data-filter="rows" placeholder="Reels durchsuchen ..."></label><button class="filter-chip active">Alle 20</button><button class="filter-chip">Online</button><button class="filter-chip">Entwürfe</button></div><section class="table-panel"><div class="table-head"><span>REEL</span><span>STATUS</span><span>AUFRUFE</span><span>LIKES</span><span></span></div>${reelRows}</section></div>`,
scripts:`<div class="page-view"><header class="page-top"><div><small>TEXTWERKSTATT</small><h1>Skripte</h1><p>Entwickle Hooks, Geschichten und klare Handlungsaufforderungen.</p></div><div class="page-actions"><button class="ui-button">Vorlagen</button><button class="ui-button primary-action" data-action="new-script">＋ Neues Skript</button></div></header><div class="editor-layout"><section class="editor-panel"><header><h2>Aktueller Entwurf</h2><div class="editor-tools"><button>B</button><button><i>I</i></button><button>☷</button></div></header><div class="editor-text" contenteditable="true"><h3>Warum dein Reel nicht wächst</h3><p><strong>HOOK</strong><br>Du machst diesen einen Fehler bei deinen Reels – und merkst es nicht einmal.</p><p><strong>HAUPTTEIL</strong><br>Viele Creator starten direkt mit der Erklärung. Beginne stattdessen mit dem Ergebnis, das dein Publikum erreichen möchte.</p><p><strong>CALL TO ACTION</strong><br>Speichere dieses Reel und teste den Hook bei deinem nächsten Video.</p></div><button class="ui-button primary-action" data-action="save">Skript speichern</button></section><aside class="side-stack"><div class="info-panel"><h3>Skript-Details</h3><div class="info-row"><span>Wörter</span><strong>86</strong></div><div class="info-row"><span>Dauer</span><strong>ca. 28 Sek.</strong></div><div class="info-row"><span>Fortschritt</span><strong>72%</strong></div></div><div class="info-panel"><h3>Letzte Skripte</h3>${scripts.slice(0,3).map(s=>`<div class="info-row"><span>${s[0]}</span><strong>→</strong></div>`).join('')}</div></aside></div><section class="table-panel"><div class="table-head"><span>SKRIPT</span><span>STATUS</span><span>UMFANG</span><span>DAUER</span><span></span></div>${scriptRows}</section></div>`,
competitors:`<div class="page-view competitors-page"><header class="page-top"><div><small>MARKTBEOBACHTUNG</small><h1>Wettbewerber</h1><p>Vergleiche Reichweite, Wachstum und erfolgreiche Formate.</p></div><div class="page-actions"><button class="ui-button primary-action" data-action="add-competitor">＋ Wettbewerber</button></div></header><div class="filter-bar"><label>⌕<input data-filter="competitors" placeholder="Wettbewerber suchen ..."></label><button class="filter-chip active">Alle 20</button><button class="filter-chip">Wachsend</button></div><div class="competitor-grid" data-competitor-grid>${competitors}</div></div>`,
settings:`<div class="page-view settings-page"><header class="page-top"><div><small>KONTO & APP</small><h1>Einstellungen</h1><p>Verwalte Profil, Benachrichtigungen und Arbeitsbereich.</p></div><div class="page-actions"><button class="ui-button primary-action" data-action="save">Änderungen speichern</button></div></header><div class="settings-layout"><nav class="settings-menu"><button class="active">Profil</button><button>Benachrichtigungen</button><button>Integrationen</button><button>Sicherheit</button></nav><section class="settings-panel"><h2>Profil</h2><p>Deine persönlichen Informationen und Standardeinstellungen.</p><div class="form-row"><label><strong>Anzeigename</strong><small>Sichtbar in deinem Arbeitsbereich</small></label><input value="Leo Rosen"></div><div class="form-row"><label><strong>E-Mail</strong><small>Adresse für Benachrichtigungen</small></label><input type="email" value="leo@beispiel.de"></div><div class="form-row"><label><strong>Sprache</strong><small>Sprache der Benutzeroberfläche</small></label><select><option>Deutsch</option><option>English</option></select></div><div class="form-row"><label><strong>Trend-Benachrichtigungen</strong><small>Wöchentliche Empfehlungen erhalten</small></label><button class="toggle on" data-toggle><i></i></button></div><div class="form-row"><label><strong>Auto-Speichern</strong><small>Skripte automatisch sichern</small></label><button class="toggle on" data-toggle><i></i></button></div></section></div></div>`
};

let detailReturnView='dashboard',overviewContext='dashboard';
function getSavedReel(title){try{return JSON.parse(localStorage.getItem(`inter-reel:${title}`))||{}}catch{return{}}}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]))}
function scriptWorkspaceTemplate(){const saved=key=>{try{return localStorage.getItem(`inter-script-block:${key}`)||''}catch{return''}};const block=(key,title,content,comment,author,time)=>`<article class="reference-script-block" data-script-block="${key}"><header><div><h2>${title}</h2><small>Redaktionsblock</small></div><button data-script-block-edit>✎ Bearbeiten</button></header><div class="reference-block-editor" data-script-block-content>${saved(key)?`<p class="saved-copy">${escapeHtml(saved(key))}</p>`:content}</div><footer><small>⌁ Kommentar</small><p>${comment}</p><span>— ${author}<b>${time}</b></span></footer></article>`;return `<div class="page-view script-reference-page"><header class="script-workspace-head"><div><small>ÜBERSICHT / KI-ANALYSE / ERFOLGREICHE REELS</small><h1>3 Fehler, die deine Reichweite zerstören</h1></div><div><button data-script-action="export">↗ Exportieren⌄</button><button class="remix-button" data-script-action="remix">Remix</button><button data-script-action="more">•••</button></div></header><div class="script-reference-layout"><main class="script-block-list">${block('hook','Hook','<p>Die meisten Reels scheitern an genau diesen drei Fehlern ...</p>','Starker Einstieg. Funktioniert gut durch Kontrast und Neugier.','Alex','vor 2 Std.')} ${block('script','Skript','<p><strong>Fehler Nr. 1 — ein langweiliger Hook.</strong> Wenn du in den ersten 1–2 Sekunden nicht fesselst, wird weitergescrollt.</p><p><strong>Fehler Nr. 2 — zu viel Einleitung.</strong> Menschen schauen sich lange Erklärungen nicht bis zum Ende an.</p><p><strong>Fehler Nr. 3 — kein klares CTA.</strong> Ohne Handlungsaufforderung gibt es weder Likes noch neue Follower.</p>','Die Struktur ist klar. Beispiele noch etwas konkreter machen.','Maja','vor 1 Std.')} ${block('cta','Call to Action','<p>Speichere dieses Reel, damit du diese Fehler nicht wiederholst. Folge uns für weitere praktische Reels-Tipps.</p>','Kurz, verständlich und handlungsorientiert.','Leo','vor 20 Min.')}</main><aside class="source-panel"><h2>Quelle</h2><p>@reels.master<br><span>12. Mai 2026</span></p><div class="source-cover"><strong>3</strong><b>FEHLER,<br>DIE DEINE<br>REICHWEITE<br>ZERSTÖREN</b></div><div class="source-stats"><span>▷ 1,2M</span><span>♡ 14,2K</span></div><div class="source-meta"><h3>Tags</h3><div><span>Fehler</span><span>Reels</span><span>Reichweite</span></div><h3>Dauer</h3><p>00:28</p></div></aside></div></div>`}
views.scripts=scriptWorkspaceTemplate();
function reelDetailTemplate(title,views){const saved=getSavedReel(title);const displayTitle=saved.title||title;const description=saved.description||'So fesselst du deine Zuschauer in den ersten drei Sekunden und führst sie sicher durch deine Story.';const script=saved.script||'Hallo! Heute sprechen wir über Trends. Starte mit einem starken Hook, zeige sofort den wichtigsten Nutzen und führe dein Publikum Schritt für Schritt durch die Story ...';return `<div class="page-view detail-page" data-original-title="${escapeHtml(displayTitle)}" data-source-title="${escapeHtml(title)}"><div class="detail-toolbar"><button class="back-button" data-detail-back>← Zurück</button><span>REEL-DETAILS</span><button class="detail-edit" data-detail-edit>Bearbeiten</button><div class="detail-save-actions" hidden><button data-detail-cancel>Abbrechen</button><button class="save" data-detail-save>Speichern</button></div></div><section class="detail-grid"><article class="detail-card detail-video"><header><h1>Beliebtes Reel</h1><span class="detail-status">Online</span></header><div class="detail-video-frame"><div class="detail-person"></div><button class="detail-play" data-detail-play>▶</button><span>00:30</span></div><div class="detail-video-copy"><h2 data-edit-field="title">${escapeHtml(displayTitle)}</h2><p data-edit-field="description">${escapeHtml(description)}</p><div><span>Trends</span><span>Tipps</span><strong>◉ ${views||'42,8K'}　♡ 3,2K</strong></div></div></article><article class="detail-card detail-script"><header><h1>Skript</h1><span class="saved"><i></i>Gespeichert</span></header><div class="detail-script-copy"><span>“</span><p data-edit-field="script">${escapeHtml(script)}</p></div><div class="detail-script-bottom"><small>FORTSCHRITT <b>72%</b></small><div><i></i></div><button data-detail-edit>Bearbeiten</button></div></article><article class="detail-card detail-analytics"><header><h1>Analyse</h1><span>30 Tage</span></header><div class="detail-metrics"><div><span>Aufrufe</span><strong>${views||'152K'}</strong></div><div><span>Likes</span><strong>8,4K</strong></div><div><span>Kommentare</span><strong>1,2K</strong></div><div><span>Wachstum</span><strong>↑ 1,5%</strong></div></div><div class="detail-chart"><svg viewBox="0 0 500 110" preserveAspectRatio="none"><path d="M0 96L42 90L75 75L108 79L142 61L172 70L215 48L250 58L286 39L320 48L355 29L391 37L430 18L462 24L500 8"/></svg></div></article></section></div>`}
function openReel(title,views,returnView='dashboard'){detailReturnView=returnView;sessionStorage.setItem('inter:lastReel',JSON.stringify({title,views,returnView}));dashboardView.hidden=true;viewRoot.hidden=false;viewRoot.innerHTML=reelDetailTemplate(title,views);document.querySelectorAll('.nav-item').forEach(link=>link.classList.remove('active'));history.replaceState(null,'','#reel');toggleMenu(false)}
function setDetailEditing(editing){const page=viewRoot.querySelector('.detail-page');if(!page)return;page.classList.toggle('editing',editing);page.querySelectorAll('[data-edit-field]').forEach(field=>{field.contentEditable=String(editing);field.setAttribute('spellcheck','true')});page.querySelectorAll('[data-detail-edit]').forEach(button=>button.hidden=editing);page.querySelector('.detail-save-actions').hidden=!editing;if(editing){page.dataset.snapshot=JSON.stringify([...page.querySelectorAll('[data-edit-field]')].map(field=>field.innerText));page.querySelector('[data-edit-field="title"]').focus()}}
function showView(name,updateHash=true){const usesOverview=name==='dashboard'||name==='trends';dashboardView.hidden=!usesOverview;viewRoot.hidden=usesOverview;if(usesOverview){overviewContext=name;document.querySelector('[data-overview-title]').textContent=name==='trends'?'Trend-Reels':'Beliebte Reels';dashboardView.setAttribute('aria-label',name==='trends'?'Trend-Reels Dashboard':'Reels Dashboard')}else viewRoot.innerHTML=name==='scripts'?scriptWorkspaceTemplate():(views[name]||views.reels);document.querySelectorAll('.nav-item').forEach(link=>link.classList.toggle('active',link.dataset.view===name));if(updateHash)history.replaceState(null,'',`#${name}`);toggleMenu(false)}
document.querySelectorAll('.nav-item').forEach(item=>item.addEventListener('click',event=>{event.preventDefault();showView(item.dataset.view)}));
document.querySelectorAll('.brand,.mobile-header a').forEach(link=>link.addEventListener('click',event=>{event.preventDefault();showView('dashboard')}));
viewRoot.addEventListener('click',event=>{const action=event.target.closest('[data-action]')?.dataset.action;if(action){if(action==='new')modal.showModal();else if(action==='new-script')notify('Neues Skript wurde angelegt');else if(action==='save')notify('Änderungen wurden gespeichert');else if(action==='add-competitor')notify('Wettbewerber kann jetzt hinzugefügt werden');else if(action==='options')notify('Weitere Optionen geöffnet');return}const open=event.target.closest('[data-open-reel]');if(open){openReel(open.dataset.title,open.dataset.views,location.hash.replace('#','')||'trends');return}if(event.target.closest('[data-detail-back]')){showView(detailReturnView);return}if(event.target.closest('[data-detail-edit]')){setDetailEditing(true);return}if(event.target.closest('[data-detail-cancel]')){const page=viewRoot.querySelector('.detail-page');const snapshot=JSON.parse(page.dataset.snapshot||'[]');page.querySelectorAll('[data-edit-field]').forEach((field,index)=>field.innerText=snapshot[index]||'');setDetailEditing(false);notify('Änderungen verworfen');return}if(event.target.closest('[data-detail-save]')){const page=viewRoot.querySelector('.detail-page');const fields=[...page.querySelectorAll('[data-edit-field]')].map(field=>field.innerText.trim());const data={title:fields[0]||page.dataset.originalTitle,description:fields[1],script:fields[2]};localStorage.setItem(`inter-reel:${page.dataset.sourceTitle}`,JSON.stringify(data));sessionStorage.setItem('inter:lastReel',JSON.stringify({title:page.dataset.sourceTitle,views:page.querySelector('.detail-metrics strong').innerText,returnView:detailReturnView}));setDetailEditing(false);page.querySelector('.saved').innerHTML='<i></i>Gespeichert';notify('Reel wurde gespeichert');return}const play=event.target.closest('[data-detail-play]');if(play){play.classList.toggle('playing');play.textContent=play.classList.contains('playing')?'Ⅱ':'▶';notify(play.classList.contains('playing')?'Vorschau wird abgespielt':'Vorschau pausiert');return}const toggle=event.target.closest('[data-toggle]');if(toggle)toggle.classList.toggle('on');const chip=event.target.closest('.filter-chip');if(chip){chip.parentElement.querySelectorAll('.filter-chip').forEach(item=>item.classList.remove('active'));chip.classList.add('active')}});
viewRoot.addEventListener('click',event=>{const editButton=event.target.closest('[data-script-block-edit]');if(editButton){const block=editButton.closest('[data-script-block]');const content=block.querySelector('[data-script-block-content]');const editing=block.classList.toggle('editing');content.contentEditable=String(editing);editButton.textContent=editing?'✓ Speichern':'✎ Bearbeiten';if(editing){content.focus();notify(`${block.querySelector('h2').textContent} kann jetzt bearbeitet werden`)}else{localStorage.setItem(`inter-script-block:${block.dataset.scriptBlock}`,content.innerText.trim());notify(`${block.querySelector('h2').textContent} wurde gespeichert`)}return}const scriptAction=event.target.closest('[data-script-action]')?.dataset.scriptAction;if(scriptAction==='export')notify('Export wird vorbereitet');else if(scriptAction==='remix')notify('Eine neue Remix-Version wurde erstellt');else if(scriptAction==='more')notify('Weitere Optionen geöffnet')});
viewRoot.addEventListener('input',event=>{const mode=event.target.dataset.filter;if(!mode)return;const query=event.target.value.toLowerCase();const selector=mode==='cards'?'.content-card':mode==='rows'?'.table-row':'.competitor';viewRoot.querySelectorAll(selector).forEach(item=>item.hidden=!item.textContent.toLowerCase().includes(query))});
const initialView=location.hash.replace('#','');if(['trends','reels','scripts','competitors','settings'].includes(initialView))showView(initialView,false);else if(initialView==='reel'){try{const last=JSON.parse(sessionStorage.getItem('inter:lastReel'));if(last)openReel(last.title,last.views,last.returnView)}catch{showView('dashboard',false)}}
document.querySelector('[data-edit]').addEventListener('click',()=>{const script=document.querySelector('#scriptContent');script.contentEditable='true';script.focus();notify('Du kannst das Skript jetzt bearbeiten')});
const periods=[{label:'7 Tage',values:['38,9K','2,1K','327','0,4%']},{label:'30 Tage',values:['152K','8,4K','1,2K','1,5%']},{label:'90 Tage',values:['428K','24K','3,7K','4,8%']}];let periodIndex=1;
document.querySelector('[data-period]').addEventListener('click',event=>{periodIndex=(periodIndex+1)%periods.length;const current=periods[periodIndex];event.currentTarget.textContent=`${current.label}⌄`;['views','likes','comments','growth'].forEach((key,index)=>document.querySelector(`[data-metric="${key}"]`).textContent=current.values[index]);notify(`Analyse: ${current.label}`)});
document.querySelectorAll('[data-toast]').forEach(button=>button.addEventListener('click',event=>{event.preventDefault();notify(button.dataset.toast)}));
document.querySelectorAll('[data-new]').forEach(button=>button.addEventListener('click',()=>modal.showModal()));document.querySelectorAll('[data-choice]').forEach(button=>button.addEventListener('click',()=>{modal.close();notify(`${button.dataset.choice} wurde ausgewählt`)}));modal.addEventListener('click',event=>{if(event.target===modal)modal.close()});document.addEventListener('keydown',event=>{if(event.key==='Escape')toggleMenu(false)});
