const sidebar=document.querySelector('#sidebar'),menu=document.querySelector('#menuButton'),backdrop=document.querySelector('#backdrop'),modal=document.querySelector('#modal'),toast=document.querySelector('#toast');let timer;
function notify(message){clearTimeout(timer);toast.querySelector('p').textContent=message;toast.classList.add('visible');timer=setTimeout(()=>toast.classList.remove('visible'),2600)}
function toggleMenu(force){const open=typeof force==='boolean'?force:!sidebar.classList.contains('open');sidebar.classList.toggle('open',open);backdrop.classList.toggle('visible',open);menu.setAttribute('aria-expanded',String(open));document.body.style.overflow=open?'hidden':''}
menu.addEventListener('click',()=>toggleMenu());backdrop.addEventListener('click',()=>toggleMenu(false));
document.querySelectorAll('.nav-item').forEach(item=>item.addEventListener('click',event=>{if(!document.querySelector(item.getAttribute('href'))){event.preventDefault();notify(`${item.dataset.placeholder} wird als Nächstes eingerichtet`)}document.querySelectorAll('.nav-item').forEach(link=>link.classList.remove('active'));item.classList.add('active');toggleMenu(false)}));
const reels=[
  ['Hook in 3 Sekunden','@creatorlab','00:24','42,8K',98],['Storytelling-Formel','@socialtips','00:31','37,2K',91],['Content ohne Stress','@reelstudio','00:18','29,4K',86],['Die perfekte Caption','@marketingde','00:27','24,9K',79],['Mehr Reichweite','@growdaily','00:22','18,7K',72],
  ['5 Fehler bei Reels','@contentcoach','00:34','17,3K',70],['Der perfekte Einstieg','@hookmaster','00:19','16,8K',68],['Algorithmus einfach erklärt','@digitalwissen','00:42','15,1K',65],['Mehr Kommentare erhalten','@communitypro','00:25','13,9K',63],['Reels richtig planen','@planstudio','00:29','12,6K',61],
  ['Licht für dein Video','@filmtipps','00:21','11,8K',59],['Schneller Videoschnitt','@editacademy','00:37','10,9K',57],['Ideen für jeden Tag','@ideenwerk','00:26','9,7K',54],['Call-to-Action Vorlage','@conversionlab','00:20','8,8K',52],['Trend-Audio finden','@soundscout','00:23','7,9K',49],
  ['Kamera richtig einstellen','@videosetup','00:32','7,1K',47],['Bessere Untertitel','@captionpro','00:28','6,4K',44],['Authentisch vor der Kamera','@creatorlife','00:39','5,8K',41],['Reels mehrfach verwenden','@contentflow','00:30','5,2K',38],['Deine Wochenstrategie','@socialplan','00:45','4,7K',35]
];
const reelList=document.querySelector('#reelList'),reelSearch=document.querySelector('#reelSearch'),emptyState=document.querySelector('#emptyState');
function renderReels(query=''){const normalized=query.trim().toLowerCase();const visible=reels.filter(reel=>`${reel[0]} ${reel[1]}`.toLowerCase().includes(normalized));reelList.innerHTML=visible.map((reel,index)=>`<button class="reel-row ${reel[0]==='Hook in 3 Sekunden'?'selected':''}" data-reel="${reel[0]}" data-views="${reel[3]}"><span class="thumb t${index%5+1}"><i></i></span><span><strong>${reel[0]}</strong><small>${reel[1]} · ${reel[2]}</small></span><em><b>${reel[4]}%</b><i style="background:linear-gradient(90deg,#6e5de2 0 ${reel[4]}%,#e6e6eb ${reel[4]}%)"></i></em></button>`).join('');emptyState.classList.toggle('visible',visible.length===0)}
renderReels();
reelSearch.addEventListener('input',()=>renderReels(reelSearch.value));
reelList.addEventListener('click',event=>{const row=event.target.closest('.reel-row');if(!row)return;document.querySelectorAll('.reel-row').forEach(item=>item.classList.remove('selected'));row.classList.add('selected');document.querySelector('#selectedTitle').textContent=row.dataset.reel;document.querySelector('#selectedViews').textContent=row.dataset.views;notify(`${row.dataset.reel} ausgewählt`)});
document.querySelector('[data-edit]').addEventListener('click',()=>{const script=document.querySelector('#scriptContent');script.contentEditable='true';script.focus();notify('Du kannst das Skript jetzt bearbeiten')});
const periods=[{label:'7 Tage',values:['38,9K','2,1K','327','0,4%']},{label:'30 Tage',values:['152K','8,4K','1,2K','1,5%']},{label:'90 Tage',values:['428K','24K','3,7K','4,8%']}];let periodIndex=1;
document.querySelector('[data-period]').addEventListener('click',event=>{periodIndex=(periodIndex+1)%periods.length;const current=periods[periodIndex];event.currentTarget.textContent=`${current.label}⌄`;['views','likes','comments','growth'].forEach((key,index)=>document.querySelector(`[data-metric="${key}"]`).textContent=current.values[index]);notify(`Analyse: ${current.label}`)});
document.querySelectorAll('[data-toast]').forEach(button=>button.addEventListener('click',event=>{event.preventDefault();notify(button.dataset.toast)}));
document.querySelectorAll('[data-new]').forEach(button=>button.addEventListener('click',()=>modal.showModal()));document.querySelectorAll('[data-choice]').forEach(button=>button.addEventListener('click',()=>{modal.close();notify(`${button.dataset.choice} wurde ausgewählt`)}));modal.addEventListener('click',event=>{if(event.target===modal)modal.close()});document.addEventListener('keydown',event=>{if(event.key==='Escape')toggleMenu(false)});
